name: local_moko_development

include:
  - infrastructure.yaml
  - platform-services.yaml
  - game-services.yaml
  - frontend.yaml
  - black-box-chess-game.yaml

networks:
  moko_kc:
    name: moko-kc-network
    driver: bridge
  moko_backend:
    name: moko-back-network
    driver: bridge