server.port: 8088

spring:
  application:
    name: game-acl-service

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:password}

logging:
  level:
    sql: ${LOGGING_LEVEL_SQL:debug}
    web: ${LOGGING_LEVEL_WEB:debug}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          WARNING: 200
          DOWN: 503
          OUT_OF_SERVICE: 503

business:
  game-service:
    url: ${GAME_SERVICE_URL:http://localhost:8084}
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8089}

acl-config:
  backend-url: ${ACL_CONFIG_BACKEND_URL:http://host.docker.internal:8088}
  chess-info:
    backend-url: ${CHESS_INFO_BACKEND_URL:http://localhost:8080}
    price: 79.99
    category: PARTY