server.port: 8088

spring:
  application:
    name: game-acl-service

rabbitmq:
  platform:
    host: ${RABBITMQ_PLATFORM_HOST:localhost}
    port: ${RABBITMQ_PLATFORM_PORT:5672}
    username: ${RABBITMQ_PLATFORM_USERNAME:user}
    password: ${RABBITMQ_PLATFORM_PASSWORD:password}
  chess:
    host: ${RABBITMQ_CHESS_HOST:localhost}
    port: ${RABBITMQ_CHESS_PORT:5673}
    username: ${RABBITMQ_CHESS_USERNAME:user}
    password: ${RABBITMQ_CHESS_PASSWORD:password}

logging:
  level:
    sql: ${LOGGING_LEVEL_SQL:debug}
    web: ${LOGGING_LEVEL_WEB:debug}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          WARNING: 200
          DOWN: 503
          OUT_OF_SERVICE: 503